#- * -coding: utf - 8 - * -#Generated by Django 1.9.4 on 2016 - 06 - 02 14: 54
from __future__
import unicode_literals

import Athena.models
from django.conf
import settings
from django.db
import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

dependencies = [
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
]

operations = [
    migrations.CreateModel(
        name = 'Aluno',
        fields = [
            ('id', models.AutoField(auto_created = True,
                primary_key = True,
                serialize = False,
                verbose_name = 'ID')), ('Id', models.CharField(help_text =
                b 'Id do Aluno', max_length = 50)), ('nome', models.CharField(
                help_text = b 'Nome do Aluno', max_length = 50)), ('user',
                models.ForeignKey(help_text = b 'Usu\xc3\xa1rio de login relacionado ao Aluno',
                    on_delete = django.db.models.deletion.CASCADE, to =
                    settings.AUTH_USER_MODEL)),
        ],
    ),
    migrations.CreateModel(
        name = 'Atividade',
        fields = [
            ('id', models.AutoField(auto_created = True,
                primary_key = True, serialize = False, verbose_name =
                'ID')), ('Id', models.CharField(help_text = b 'Id da Submissao',
                max_length = 50)), ('nome', models.CharField(max_length =
                50)), ('descricao', models.CharField(max_length = 1000)), (
                'restricoes', models.CharField(max_length = 1000)), (
                'arquivo_roteiro', models.FileField(
                    upload_to = Athena.models.atividade_path)), (
                'arquivo_entrada', models.FileField(
                    upload_to = Athena.models.atividade_path)), (
                'arquivo_entrada2', models.FileField(
                    upload_to = Athena.models.atividade_path)), (
                'arquivo_saida', models.FileField(
                    upload_to = Athena.models.atividade_path)), (
                'arquivo_saida2', models.FileField(
                    upload_to = Athena.models.atividade_path)), ('peso1',
                models.IntegerField(
                    default = 1)), ('peso2', models.IntegerField(
                default = 1)), ('data_limite', models.DateField()),
        ],
    ),
    migrations.CreateModel(
        name = 'Professor',
        fields = [
            ('id', models.AutoField(auto_created = True,
                primary_key = True, serialize = False, verbose_name =
                'ID')), ('Id', models.CharField(help_text = b 'Id do Professor',
                max_length = 50)), ('nome', models.CharField(
                help_text = b 'Nome do Professor', max_length = 50)), (
                'user', models.ForeignKey(help_text = b 'Usu\xc3\xa1rio de login relacionado ao Professor',
                    on_delete = django.db.models.deletion.CASCADE, to =
                    settings.AUTH_USER_MODEL)),
        ],
    ),
    migrations.CreateModel(
        name = 'RelAlunoAtividade',
        fields = [
            ('id', models.AutoField(auto_created = True,
                primary_key = True, serialize = False, verbose_name =
                'ID')), ('foiEntregue', models.BooleanField(
                help_text = b 'Se o aluno j\xc3\xa1 mandou alguma submiss\xc3\xa3o para a atividade'
            )), ('aluno', models.ForeignKey(help_text = b 'Aluno inscrito na atividade',
                on_delete = django.db.models.deletion.CASCADE, to =
                'Athena.Aluno')), ('atividade', models.ForeignKey(help_text =
                b 'Atividade do aluno',
                on_delete = django.db.models.deletion.CASCADE, to =
                'Athena.Atividade')),
        ],
    ),
    migrations.CreateModel(
        name = 'Submissao',
        fields = [
            ('id', models.AutoField(auto_created = True,
                primary_key = True, serialize = False, verbose_name =
                'ID')), ('data_envio', models.DateField(auto_now = True,
                help_text = b 'Data de submiss\xc3\xa3o do c\xc3\xb3digo'
            )), ('arquivo_codigo', models.FileField(
                upload_to = Athena.models.submissao_path)), ('resultado',
                models.CharField(choices = [(b 'AC', b 'Aceito'), (b 'TLE',
                        b 'Tempo Limite Excedido'), (b 'RTE', b 'Erro em tempo de execu\xc3\xa7\xc3\xa3o'), (
                        b 'CE', b 'Erro de compila\xc3\xa7\xc3\xa3o'), (
                        b 'WA', b 'Resposta Errada'), (b 'INV', b 'C\xc3\xb3digo Inv\xc3\xa1lido')],
                    help_text = b 'Resultado da submissao do aluno',
                    max_length = 3)), ('nota', models.PositiveSmallIntegerField(
                help_text = b 'Nota para submiss\xc3\xa3o do aluno')), (
                'aluno', models.ForeignKey(help_text = b 'Aluno que enviou a submiss\xc3\xa3o',
                    on_delete = django.db.models.deletion.CASCADE, to =
                    'Athena.Aluno')), ('atividade', models.ForeignKey(
                help_text = b 'Atividade relacionada a submiss\xc3\xa3o',
                on_delete = django.db.models.deletion.CASCADE, to =
                'Athena.Atividade')),
        ],
    ),
    migrations.CreateModel(
        name = 'Turma',
        fields = [
            ('id', models.AutoField(auto_created = True,
                primary_key = True, serialize = False, verbose_name =
                'ID')), ('Id', models.CharField(help_text = b 'Id da Turma',
                max_length = 50)), ('nome', models.CharField(max_length =
                50)), ('descricao', models.CharField(max_length = 2000)), (
                'alunos', models.ManyToManyField(blank = True,
                    help_text = b 'Alunos inscritos na turma', to =
                    'Athena.Aluno')), ('professor', models.ForeignKey(
                help_text = b 'Professor da Turma',
                on_delete = django.db.models.deletion.CASCADE, to =
                'Athena.Professor')),
        ],
    ),
    migrations.AddField(
        model_name = 'atividade',
        name = 'alunos',
        field = models.ManyToManyField(blank = True, help_text = b 'Relacao do aluno com a atividade,\n            guarda se aluno submeteu atividade',
            through = 'Athena.RelAlunoAtividade', to = 'Athena.Aluno'),
    ),
    migrations.AddField(
        model_name = 'atividade',
        name = 'turma',
        field = models.ForeignKey(help_text = b 'Turma a qual a atividade pertence',
            on_delete = django.db.models.deletion.CASCADE, to =
            'Athena.Turma'),
    ),
]