# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-19 13:58
from __future__ import unicode_literals

import Athena.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Athena', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='arquivo_testador',
            field=models.FileField(default=1, upload_to=Athena.models.atividade_path),
            preserve_default=False,
        ),
    ]
