# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-08 01:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Athena', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='Id',
            field=models.IntegerField(default=1, help_text=b'Id do Aluno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividade',
            name='Id',
            field=models.IntegerField(default=1, help_text=b'Id da Atividade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='Id',
            field=models.IntegerField(default=1, help_text=b'Id do Professor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turma',
            name='Id',
            field=models.IntegerField(default=1, help_text=b'Id da Turma'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='user',
            field=models.ForeignKey(
                help_text=b'Usu\xc3\xa1rio de login relacionado ao Aluno',
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='professor',
            name='user',
            field=models.ForeignKey(
                help_text=b'Usu\xc3\xa1rio de login relacionado ao Professor',
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relalunoatividade',
            name='foiEntregue',
            field=models.BooleanField(
                help_text=b'Se o aluno j\xc3\xa1 mandou" + \
                 alguma submiss\xc3\xa3o para a atividade'),
        ),
        migrations.AlterField(
            model_name='submissao',
            name='aluno',
            field=models.ForeignKey(
                help_text=b'Aluno que enviou a submiss\xc3\xa3o',
                on_delete=django.db.models.deletion.CASCADE,
                to='Athena.Aluno'),
        ),
        migrations.AlterField(
            model_name='submissao',
            name='atividade',
            field=models.ForeignKey(
                help_text=b'Atividade relacionada a submiss\xc3\xa3o',
                on_delete=django.db.models.deletion.CASCADE,
                to='Athena.Atividade'),
        ),
        migrations.AlterField(
            model_name='submissao',
            name='data_envio',
            field=models.DateField(
                auto_now=True,
                help_text=b'Data de submiss\xc3\xa3o do c\xc3\xb3digo'),
        ),
        migrations.AlterField(
            model_name='submissao',
            name='nota',
            field=models.PositiveSmallIntegerField(
                help_text=b'Nota para submiss\xc3\xa3o do aluno'),
        ),
        migrations.AlterField(
            model_name='submissao',
            name='resultado',
            field=models.CharField(
                choices=[
                    (b'AC',
                     b'Aceito'),
                    (b'TLE',
                     b'Tempo Limite Excedido'),
                    (b'RTE',
                     b'Erro em tempo de execu\xc3\xa7\xc3\xa3o'),
                    (b'CE',
                     b'Erro de compila\xc3\xa7\xc3\xa3o'),
                    (b'WA',
                     b'Resposta Errada')],
                help_text=b'Resultado da submissao do aluno',
                max_length=3),
        ),
    ]
