# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-23 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Athena', '0002_atividade_arquivo_testador'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='teste_customizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atividade',
            name='teste_privado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submissao',
            name='resultado',
            field=models.CharField(choices=[(b'AC', b'Resposta correta'), (b'AC2', b'Teste do professor executado com sucesso'), (b'TLE', b'Tempo Limite Excedido'), (b'RTE', b'Erro em tempo de execu\xc3\xa7\xc3\xa3o'), (b'CE', b'Erro de compila\xc3\xa7\xc3\xa3o'), (b'WA', b'Erro no teste p\xc3\xbablico'), (b'WA2', b'Erro no teste privado'), (b'INV', b'C\xc3\xb3digo Inv\xc3\xa1lido'), (b'NE', b'N\xc3\xa3o entregue')], help_text=b'Resultado da submissao do aluno', max_length=3),
        ),
    ]
