# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-08 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Athena', '0002_auto_20160508_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='Id',
            field=models.CharField(help_text=b'Id do Aluno', max_length=50),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='Id',
            field=models.CharField(help_text=b'Id da Submissao', max_length=50),
        ),
        migrations.AlterField(
            model_name='professor',
            name='Id',
            field=models.CharField(help_text=b'Id do Professor', max_length=50),
        ),
        migrations.AlterField(
            model_name='turma',
            name='Id',
            field=models.CharField(help_text=b'Id da Turma', max_length=50),
        ),
    ]
