# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-02 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Athena', '0004_atividade_restricoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='alunos',
            field=models.ManyToManyField(blank=True, help_text=b'Relacao do aluno com a atividade,\n            guarda se aluno submeteu atividade', through='Athena.RelAlunoAtividade', to='Athena.Aluno'),
        ),
        migrations.AlterField(
            model_name='relalunoatividade',
            name='foiEntregue',
            field=models.BooleanField(help_text=b'Se o aluno j\xc3\xa1 mandou alguma submiss\xc3\xa3o para a atividade'),
        ),
        migrations.AlterField(
            model_name='submissao',
            name='resultado',
            field=models.CharField(choices=[(b'AC', b'Aceito'), (b'TLE', b'Tempo Limite Excedido'), (b'RTE', b'Erro em tempo de execu\xc3\xa7\xc3\xa3o'), (b'CE', b'Erro de compila\xc3\xa7\xc3\xa3o'), (b'WA', b'Resposta Errada'), (b'INV', b'C\xc3\xb3digo Inv\xc3\xa1lido')], help_text=b'Resultado da submissao do aluno', max_length=3),
        ),
    ]
