# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-08 00:41
from __future__ import unicode_literals

import Athena.models
from django.db import migrations, models
import django_dropbox.storage


class Migration(migrations.Migration):

    dependencies = [
        ('Athena', '0006_auto_20160707_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissao',
            name='arquivo_codigo',
            field=models.FileField(default=None, null=True, storage=django_dropbox.storage.DropboxStorage(), upload_to=Athena.models.atividade_path),
        ),
    ]
